import { Router } from "express";
import { authRoutes } from "./authRoutes.js";
import { activityRoutes } from "./activityRoutes.js";
import { applicationRoutes } from "./applicationRoutes.js";
import { analyticsRoutes } from "./analyticsRoutes.js";
import { careerTwinRoutes } from "./careerTwinRoutes.js";
import { cofounderRoutes } from "./cofounderRoutes.js";
import { connectionRoutes } from "./connectionRoutes.js";
import { communityRoutes } from "./communityRoutes.js";
import { feedbackRoutes } from "./feedbackRoutes.js";
import { hackathonTeamRoutes } from "./hackathonTeamRoutes.js";
import { innovationScoreRoutes } from "./innovationScoreRoutes.js";
import { matchRoutes } from "./matchRoutes.js";
import { mentorRoutes } from "./mentorRoutes.js";
import { messageRoutes } from "./messageRoutes.js";
import { notificationRoutes } from "./notificationRoutes.js";
import { opportunityRoutes } from "./opportunityRoutes.js";
import { profileRoutes } from "./profileRoutes.js";
import { portfolioRoutes } from "./portfolioRoutes.js";
import { projectHealthRoutes } from "./projectHealthRoutes.js";
import { projectRoutes } from "./projectRoutes.js";
import { recommendationRoutes } from "./recommendationRoutes.js";
import { researchHubRoutes } from "./researchHubRoutes.js";
import { roadmapRoutes } from "./roadmapRoutes.js";
import { resumeAnalyzerRoutes } from "./resumeAnalyzerRoutes.js";
import { skillExchangeRoutes } from "./skillExchangeRoutes.js";

export const apiRoutes = Router();

apiRoutes.get("/health", (_req, res) => {
  res.json({ success: true, message: "EngineerConnect AI backend running" });
});

apiRoutes.use("/", analyticsRoutes);
apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/activity", activityRoutes);
apiRoutes.use("/applications", applicationRoutes);
apiRoutes.use("/career-twin", careerTwinRoutes);
apiRoutes.use("/cofounders", cofounderRoutes);
apiRoutes.use("/connections", connectionRoutes);
apiRoutes.use("/community", communityRoutes);
apiRoutes.use("/feedback", feedbackRoutes);
apiRoutes.use("/profiles", profileRoutes);
apiRoutes.use("/portfolio", portfolioRoutes);
apiRoutes.use("/project-health", projectHealthRoutes);
apiRoutes.use("/matches", matchRoutes);
apiRoutes.use("/mentors", mentorRoutes);
apiRoutes.use("/messages", messageRoutes);
apiRoutes.use("/notifications", notificationRoutes);
apiRoutes.use("/opportunities", opportunityRoutes);
apiRoutes.use("/projects", projectRoutes);
apiRoutes.use("/hackathon-teams", hackathonTeamRoutes);
apiRoutes.use("/hackathons", hackathonTeamRoutes);
apiRoutes.use("/innovation-score", innovationScoreRoutes);
apiRoutes.use("/roadmaps", roadmapRoutes);
apiRoutes.use("/resume-analyzer", resumeAnalyzerRoutes);
apiRoutes.use("/recommendations", recommendationRoutes);
apiRoutes.use("/research-hub", researchHubRoutes);
apiRoutes.use("/skill-exchange", skillExchangeRoutes);
